[project]
name = "doni_testing"
requires-python = ">=3.7"
dependencies = [
    "python-doniclient",
    "python-ironicclient",
    "python-ironic-inspector-client"
]
dynamic = ["version"]

[project.scripts]
run_doni_inventory = "doni_testing.main:main"
