[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "doni_testing"
requires-python = ">=3.7"
dependencies = [
    "python-doniclient",
    "pyyaml==5.3.1",
    "python-ironicclient",
    "python-ironic-inspector-client",
    "humanize"
]
dynamic = ["version"]

[tool.setuptools]
packages = ["doni_testing"]

[project.scripts]
run_doni_inventory = "doni_testing.main:main"
