[tox]
min_version = 4.0
env_list = py3{8,9,10}

[testenv]
deps = pytest
commands = python3 tests/main.py

# command to set up development environment
# tested with vscode
[testenv:dev]
# install venv outside of .tox for discovery by vscode
env_dir = {tox_root}/.venv

# python version to use
basepython = py38

# install in editable mode
package = editable
# don't build sdist
no_package = true
# install dev dependencies
deps = .[dev]


[flake8]
max-line-length = 88
extend-ignore = E203
